use marcxml for importing metadata
zotero/translators pull request #1349
Opened 2017-07-02 18:32 UTC by bkroll

Just a few lines to use the MarcXML data provided through the OPACplus of Bavarian State Library instead of COinS which usually provides more detailed results and avoids punctuation problems if books have a main title and a subtitle.

This is my first try at writing Zotero translators, so any suggestions for improvements would be helpful. I'm looking forward to expand the translator for other media types or listings as well, if time permits.

2017-07-02 19:20 UTC, zuphilip commented
@bkroll Can you influence the catalogue of the BSB? My idea is that possibly this could be handled with the [unAPI translator](https://github.com/zotero/translators/blob/master/unAPI.js), when the marclink will changed such that it is detected.

For your translator here, some test cases would be good to have and can be easily added and updated with [Scaffold](https://github.com/zotero/scaffold).

2017-07-02 20:02 UTC, adam3smith commented
we also really like multiples (i.e. search results) to work for translators... Should be terribly hard to do here.

2017-07-02 20:29 UTC, bkroll commented
@zuphilip Not at all, this is just a private project.  But ok, I'll be adding some tests to the translator.

@adam3smith I'll have a look at multiples. The relevant ID number seems to be available for each list element in the HTML source, so requesting a MarcXml version of the item's metadata should work.

2021-06-08 15:36 UTC, AbeJellinek requested changes
Hey, any updates on this? Left a few comments (in addition to what others have mentioned). I would love to get this merged.

2021-06-08 15:36 UTC, AbeJellinek commented on BayerischeStaatsbibliothekOpacPlus.js
> +	"target": "^https://opacplus.bsb-muenchen.de/metaopac/singleHit.do.*",
Escape `.`s, remove the `.*` at the end.

2021-06-08 15:36 UTC, AbeJellinek commented on BayerischeStaatsbibliothekOpacPlus.js
> +	mediaTypeIcon = doc.getElementById("mediaTypeIcon");
These shouldn't be global variables - add `var`

2021-06-08 15:36 UTC, AbeJellinek commented on BayerischeStaatsbibliothekOpacPlus.js
> +	}
Add a `return false` if `mediaType == "Buch"` is false.

2021-06-08 15:36 UTC, AbeJellinek commented on BayerischeStaatsbibliothekOpacPlus.js
> +	Zotero.Utilities.doGet("https://opacplus.bsb-muenchen.de" + marcxmlLinkString, translateMarcxml);
`doGet` will handle a relative URL fine, so no need to concatenate it with the domain here.

2021-06-15 17:16 UTC, AbeJellinek commented
Closing this for lack of activity.

2021-06-15 17:16 UTC, closed without merging