Update dLibra translator.
zotero/translators pull request #2342
Opened 2021-02-26 12:04 UTC by kgronowski

Added support for dLibra 6.

2021-06-04 16:42 UTC, AbeJellinek commented
Hey, thanks for contributing this! Sorry I'm just getting to it now.

As the site's HTML says:

```html
<!--type is "document" for import all tags into zotero-->
```

But it's kind of a cop-out to import every item as `document`, and I think we can do better :) It looks like the dLibra 5 translator used the RDF - why aren't we doing that with dLibra 6? [The RDF they give us](https://demo.dl.psnc.pl/dlibra/rdf.xml?type=e&id=1243) has the correct item type. It's in Polish, so the translator will have to have a Polish -> Zotero item type mapper, but that's not a big deal.

2021-06-04 16:43 UTC, AbeJellinek requested changes

2021-06-04 16:43 UTC, AbeJellinek commented on dLibra.js
> +			trans.defaultUnknownType = 'document';
map item types instead of doing this

2021-07-28 22:32 UTC, AbeJellinek commented
Trying to test but the demo site is returning an internal server error. The first site in the tests works but looks to be dLibra 5.

2021-07-29 09:25 UTC, kgronowski commented
Thanks for the notice. dLibra 6 demo should be working fine now.

2021-07-30 21:00 UTC, AbeJellinek requested changes
Thanks! A few more comments.

2021-07-30 21:00 UTC, AbeJellinek commented on dLibra.js
> +		"type": "web",
These three tests for multiples aren't working.

2021-09-16 20:32 UTC, merged

2021-09-16 20:33 UTC, AbeJellinek commented
Thanks so much! Linted and merged.