Add translator for 知乎Zhihu
zotero/translators pull request #2710
Opened 2021-09-21 14:24 UTC by l0o0

[知乎Zhihu](https://www.zhihu.com) is a Quora-like site in China. This translator can save answers from the question page and search results. The item type is webpage, and the detailed post is saved to a note

2021-10-31 13:49 UTC, l0o0 commented
@AbeJellinek So sorry for the late reply. I've updated the code.

2021-12-30 18:28 UTC, AbeJellinek requested changes

2021-12-30 18:28 UTC, AbeJellinek commented on Zhihu.js
> +		return "webpage";
Would `forumPost` be more appropriate?

2022-01-04 03:48 UTC, l0o0 commented on Zhihu.js
> +	) return true;
Yes, your are right. The code below can return multiple results. These codes are added deliberately. Sometimes translator can not return multiple results in search, like https://www.zhihu.com/search?type=content&q=zotero). So I use url to return multiple.

2022-01-04 13:30 UTC, l0o0 commented on Zhihu.js
> +		itemInfo[url] = ZID;
I have updated these codes, new codes will be pushed tomorrow

2022-01-05 02:46 UTC, l0o0 commented
@AbeJellinek Hi, codes are updated. Thank you for your detailed review.

2023-03-23 13:58 UTC, closed without merging