fixed: airiti getDocId function
zotero/translators pull request #2855
Opened 2022-07-31 16:17 UTC by cesaryuan

fixed airiti cannot getDocId with lowercase url paramters

2022-08-02 17:28 UTC, AbeJellinek requested changes
Looks good, just remove the debug calls!

2022-08-02 17:28 UTC, AbeJellinek commented on Airiti.js
> +	Z.debug(`doWeb: ${docID}`);
This should be removed

2022-08-02 17:28 UTC, AbeJellinek commented on Airiti.js
> +	Z.debug('bibTeXUrl: ' + bibTeXUrl);
And this

2022-08-06 07:18 UTC, cesaryuan commented on Airiti.js
> +	Z.debug(`doWeb: ${docID}`);
Thank you. I have removed the calls.

2022-08-08 18:22 UTC, merged

2022-08-08 18:22 UTC, AbeJellinek commented
Thanks!