Silverchair Add chapters
zotero/translators pull request #2863
Opened 2022-08-21 19:45 UTC by adam3smith

Closes #2862

2022-08-21 19:49 UTC, adam3smith commented on Silverchair.js
> +				"title": "1Statistical inference with probabilistic graphical models",
I wasn't sure here -- I could obviously try to remove the chapter numbers in the beginning, but potentially fraught -- titles can start with numbers (*"3-D imaging in modern medicine"

2022-08-22 16:00 UTC, AbeJellinek requested changes

2022-08-22 17:41 UTC, adam3smith commented
Done -- see what you think

2022-08-22 17:49 UTC, AbeJellinek commented
Perfect!

2022-08-22 17:49 UTC, merged