Add translator for Dutch newspaper NRC
zotero/translators pull request #3055
Opened 2023-06-15 13:57 UTC by mastaal

Here's a PR for a translator for the Dutch newspaper [NRC](https://www.nrc.nl/). It works both for recent articles, as for re-published articles from their [archive](https://www.nrc.nl/index/archief/).

It's my first translator, so any feedback is much appreciated :smile:

2023-06-16 17:34 UTC, adam3smith requested changes
Some change requests -- let me know if anything isn't clear

2023-06-16 17:34 UTC, adam3smith commented on NRC.nl.js
> +
We'd really want multiples (search results, maybe section browser) included, too

2023-06-16 17:34 UTC, adam3smith commented on NRC.nl.js
> +	let item = new Zotero.Item("newspaperArticle");
You'll want to start with the embedded metadata translator, which gets you most of the below (title, language, date, description, rights, url, snapshot) already. Use the template available in the translator editor

2023-06-16 17:34 UTC, adam3smith commented on NRC.nl.js
> +
We'd want authors where they're available, e.g. Clara van de Wiel for https://www.nrc.nl/nieuws/2023/06/15/lot-van-natuurherstelwet-timmermans-blijft-erg-onzeker-na-belangrijke-stemming-a4167267

2023-06-16 20:11 UTC, mastaal commented
> Some change requests -- let me know if anything isn't clear

Thanks. This is useful feedback that I can work with.

2023-06-17 08:57 UTC, mastaal commented
@adam3smith I think 2fb7fdb resolves all your comments.

2023-06-19 02:48 UTC, adam3smith commented on NRC.nl.js
> +	else if (url.endsWith(".nl/") || url.endsWith(".nl") || url.includes("/index/") || url.includes("/search/")) {
```suggestion
	else if ((url.endsWith(".nl/") || url.endsWith(".nl") || url.includes("/index/") || url.includes("/search/")) && getSearchResults(doc, true)) {
```

The last bit prevents detecting multiples where we can't import

2023-06-19 02:49 UTC, adam3smith commented
Running the CI now to see if there are other issues -- see the nit about multiple detection above. Everything else looks great

2023-06-28 16:24 UTC, adam3smith commented
Don't worry about the failed test

2023-07-02 03:08 UTC, merged

2023-07-02 03:08 UTC, adam3smith commented
Thanks!